### ISSUE TITLE
Login Exception

### ISSUE THREAD

**Issue by thleo** [scala-exercises/scala-exercises#671] opened 2017-10-05 16:10 UTC
I logged into GitHub then clicked the link to the exercise page and received this error:

![image](https://user-images.githubusercontent.com/23345283/31237848-0b6f199a-a9c6-11e7-8062-f29164d78257.png)

Clicking another link : https://www.scala-exercises.org/scala_tutorial/terms_and_types

Then clicking *login with github* on that page resulted in successful login and no errors.

After successful login I refreshed the exercise main page and still got the exception error.

**Comment by calvellido** [comment] 2017-10-06 06:58
Hello @thleo, we have been trying to reproduce that behaviour, but we were not able to. We tried on two laptops with different configurations and by being already logged in Github before going into Scala Exercises, the other way around, etc. and the login worked

What browser/OS were you using? Can you reproduce it on a regular basis?

**Comment by thleo** [comment] 2017-10-06 15:10
I cannot reproduce the error on a regular basis though I have tried just now. I am on :
- windows 8 enterprise
- dell machine
- Version 61.0.3163.100 (Official Build) (64-bit) chrome

**Comment by calvellido** [comment] 2017-10-11 13:59
Hello @thleo, I'm gonna close this issue since we haven't found any solid evidence that can lead to this failure. Probably was a punctual GitHub login service downtime, or our server going bananas at the exact moment you logged in.

Please feel free to reopen if you encounter it again on your Scala learning path.

**Closed by calvellido** 2017-10-11 13:59 UTC
