### ISSUE TITLE
scala-exercises.org looks for snapshot versions

### ISSUE THREAD

**Issue by blandflakes** [scala-exercises/scala-exercises#814] opened 2020-06-28 21:12 UTC
When evaluating any stdlib exercise, I get:

```Evaluation failed : Unresolved Dependency : Error downloading org.scala-exercises:exercises-stdlib_2.13:0.6.0-SNAPSHOT not found: /app/.ivy2/local/org.scala-exercises/exercises-stdlib_2.13/0.6.0-SNAPSHOT/ivys/ivy.xml not found: https://repo1.maven.org/maven2/org/scala-exercises/exercises-stdlib_2.13/0.6.0-SNAPSHOT/exercises-stdlib_2.13-0.6.0-SNAPSHOT.pom not found: https://oss.sonatype.org/content/repositories/releases/org/scala-exercises/exercises-stdlib_2.13/0.6.0-SNAPSHOT/exercises-stdlib_2.13-0.6.0-SNAPSHOT.pom not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-exercises/exercises-stdlib_2.13/0.6.0-SNAPSHOT/exercises-stdlib_2.13-0.6.0-SNAPSHOT.pom```

This actually seems to be true of circe and perhaps all exercises:
```Evaluation failed : Unresolved Dependency : Error downloading org.scala-exercises:exercises-circe_2.13:0.6.0-SNAPSHOT not found: /app/.ivy2/local/org.scala-exercises/exercises-circe_2.13/0.6.0-SNAPSHOT/ivys/ivy.xml not found: https://repo1.maven.org/maven2/org/scala-exercises/exercises-circe_2.13/0.6.0-SNAPSHOT/exercises-circe_2.13-0.6.0-SNAPSHOT.pom not found: https://oss.sonatype.org/content/repositories/releases/org/scala-exercises/exercises-circe_2.13/0.6.0-SNAPSHOT/exercises-circe_2.13-0.6.0-SNAPSHOT.pom not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-exercises/exercises-circe_2.13/0.6.0-SNAPSHOT/exercises-circe_2.13-0.6.0-SNAPSHOT.pom ```

**Comment by grzegorz-bielski** [comment] 2020-06-30 14:46
I can confirm that. None of the exercises are working anymore.

**Comment by juanpedromoreno** [comment] 2020-06-30 15:13
The pipeline is blocked at the moment because we can't do new final releases due to [this issue](https://github.com/olafurpg/sbt-ci-release/issues/122). We are working on it to restore as soon as possible.

**Comment by juanpedromoreno** [comment] 2020-06-30 17:39
The issue has been fixed, could you please check again? Thanks.

Closing this for now.

**Closed by juanpedromoreno** 2020-06-30 17:39 UTC

**Comment by blandflakes** [comment] 2020-06-30 18:14
Confirmed, this is fixed. Thanks!
