### ISSUE TITLE
Database indexes

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#464] opened 2016-06-26 19:37 UTC
We need to do a pass to the most used queries and create proper indexes for those.

**Comment by dialelo** [comment] 2016-06-27 08:27
Duplicate of #415, closing that.

**Comment by raulraja** [comment] 2016-06-28 14:37
Ran a `pg:diagnose` and looks like we are in the green even after the load tests so holding back on creating extra indexes for now.
```
 △ ~ heroku pg:diagnose --app scala-exercises HEROKU_POSTGRESQL_ORANGE
Report a7620071-20b0-49b5-96d7-087d8cac33bc for scala-exercises::HEROKU_POSTGRESQL_ORANGE_URL
available for one month after creation on 2016-06-28T14:34:24.760778+00:00

GREEN: Connection Count
GREEN: Long Queries
GREEN: Idle in Transaction
GREEN: Indexes
GREEN: Bloat
GREEN: Hit Rate
GREEN: Blocking Queries
GREEN: Sequences
GREEN: Load
```

**Closed** 2016-06-28 14:37 UTC
Labels: backend, enhancement
