### ISSUE TITLE
Slash issue in top level domain

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#439] opened 2016-06-16 21:41 UTC
https://scala-exercises.org <- does not work
https://scala-exercises.org/ <- works

May be related to the new https enforcement code we deployed today

**Comment by dialelo** [comment] 2016-06-17 08:47
Hmm i couldn't reproduce this problem, does still happen to you @raulraja ?

**Comment by asoltysik** [comment] 2016-06-21 23:21
@dialelo It does to me, both in Chrome and FF.

**Comment by dialelo** [comment] 2016-06-22 10:39
It's a limitation of our DNS provider, we're moving to another in order to fix it. Will update this issue whenever we have news. In the meantime, you can access the site at [the www subdomain](https://www.scala-exercises.org).

**Comment by raulraja** [comment] 2016-06-22 11:41
Seems to be fixed now. Please wait a few hours until DNS fully propagates and report any issues you may find. So far works great on this side.

**Closed** 2016-06-22 11:41 UTC
