### ISSUE TITLE
Documentation on How to create Content for scala-exercises

### ISSUE THREAD

**Issue by juanpedromoreno** [scala-exercises/scala-exercises#545] opened 2016-07-11 10:13 UTC
At this moment, there is no information about how to create new exercises in the platform. Let's create a set of steps explaining how to do it, as well as which format should have these new exercises.

**Comment by dialelo** [comment] 2016-07-11 10:14
Dupe of #120 but with the growing interest in Scala Exercises it may be worth prioritising.

**Closed** 2016-07-11 10:28 UTC
Labels: documentation, enhancement
